site_name: Salt
site_url: https://www.mkdocs.org
site_description: Project documentation with Markdown.
site_author: Entekhab

repo_url: https://github.com/waterlili/SweatSalt.git
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        - python
